In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_excel('Consolidado_Hoteis.xlsx')

In [5]:
data.head(10)

,data_avaliacao,titulo,comentario_positivo,comentario_negativo,nota,Hotel
0,17 de fevereiro de 2025,.,A localização é perfeita e os funcionários são...,Da área de lazer que é pequena e sem uma vista...,10,Atlante_Plaza
1,30 de março de 2025,Pretenso vir oitras vezes,Atrndimento e conforto,Estacionamento pago,10,Atlante_Plaza
2,29 de março de 2025,Excepcional,"Foi excelente!! Tudo muito bom, os funcionário...",NaN,10,Atlante_Plaza
3,29 de março de 2025,Quero voltar!,"Funcionários bem treinados. Agradecemos, espec...",NaN,9,Atlante_Plaza
4,27 de março de 2025,Incrível,Excelente,NaN,10,Atlante_Plaza
5,26 de março de 2025,Agradável descanso com qualidade na Boa Viagem,"Do ambiente do hotel, do bom café da manhã ao ...",NaN,NaN,Atlante_Plaza
6,25 de março de 2025,Bom,"Localização, cafe da amanhã, acomodação",Banheiro pequeno,9,Atlante_Plaza
7,24 de março de 2025,"Ótima localização e café da manhã, já o wifi...","Do conforto da cama, da localização, do café d...","O wifi que não funcionou, mesmo depois de vári...",9,Atlante_Plaza
8,24 de março de 2025,Excepcional,"De tudo, excelente em todos os pontos.",Sem nenhum registro negativo.,10,Atlante_Plaza
9,22 de março de 2025,Muito bom,"Localização, gentileza dos funcionários.","Achei o café da manhã muito fraco, bolos, frut...",NaN,Atlante_Plaza

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95566 entries, 0 to 95565
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data_avaliacao       94047 non-null  object
 1   titulo               89833 non-null  object
 2   comentario_positivo  46621 non-null  object
 3   comentario_negativo  34717 non-null  object
 4   nota                 75428 non-null  object
 5   Hotel                95566 non-null  object
dtypes: object(6)
memory usage: 4.4+ MB

In [ ]:
import pandas as pd

# Etapa 1: Converter para datetime, tratando erros
df_consolidado['data_valida'] = pd.to_datetime(
    df_consolidado['data_avaliacao'],
    format='%d %B %Y',
    errors='coerce'  # transforma erros em NaT
)

# Etapa 2: Remover linhas onde a data está inválida (NaT)
df_consolidado = df_consolidado[df_consolidado['data_valida'].notna()]

# Etapa 3: Substituir a coluna original pela data válida, no mesmo formato textual
df_consolidado['data_avaliacao'] = df_consolidado['data_valida'].dt.strftime('%d %B %Y')

# Etapa 4: Remover a coluna auxiliar
df_consolidado.drop(columns='data_valida', inplace=True)

print("✅ Linhas com data inválida removidas e formato padronizado com sucesso.")